name: Build and upload binary artifact

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, package and upload .jar artifact
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 21
    - name: Build and package project
      run: mvn -f ./fleet/pom.xml package
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./fleet/target/fleet-fleet-demo.jar